#Written in OpenAPI https://swagger.io/specification/v2/
swagger: '2.0'
info:
  title: Cloud Endpoints + GCF
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: fitdevs-api-gateway-shkvo6h7na-uc.a.run.app
schemes:
  - https
produces:
  - application/json
security:
    - api_key: []
x-google-management:
  metrics:
    - name: "twitter-gateway-requests"
      displayName: "Twitter Bot Request Count"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      - name: "twitter-gateway-request-limit"
        metric: "twitter-gateway-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 15
paths:
  /run:
    get:
      summary: Start the bot
      operationId: run-bot
      x-google-backend:
        deadline: 3600
        protocol: h2 #Recomended for GCP Serverless backends
        address: https://twitter-bot-function-shkvo6h7na-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-quota:
        metricCosts:
          "twitter-gateway-requests": 1
      responses:
        '200':
          description: A successful response
          schema:
            type: string

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
